### ISSUE TITLE
Setup Azure Secrets

### ISSUE THREAD

**Issue by Wolftousen** [liatrio/timebot#23]
Our bot will run on Azure, need to set that up

**Comment by Wolftousen** [comment]
@blairdrummond is that snippet all we need?

**Comment by blairdrummond** [comment]
Pretty much! The subject needs to be like this, containing the repo and environment.

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#understanding-the-oidc-token

Then you just change a few things in the workflow (the `permissions` setting)

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure#adding-permissions-settings
